# python3
# repersent your orgs and repos here
# config['orgs']['cyberark']['repos']
# config['general']['branch_name']

orgs:
  cyberark:
    repos: [conjur, secretless-broker, summon]

# repersent your general configs here
general:
  branch_name: add-CODEOWNERS
  pr_name: add CODEOWNERS file
  git_add:
    - .github/CODEOWNERS
  commit_message: Adding CODEOWNERS file
  remove_tmp_dir: no
  playbook_dir: ./playbook/add-file-static
  create_branch: yes
  extra_vars:
    destination_dir: .github
    file_name: CODEOWNERS
    static_file_path: ./CODEOWNERS
